### ISSUE TITLE
Incorrect query parameters

### ISSUE THREAD

**Issue by MariusSvaCujo** [flawiddsouza/Restfox#83] opened 2023-11-27 10:27 UTC
Hi, faced this specific issue. For example if I set environment params with these values:
<img width="513" alt="image" src="https://github.com/flawiddsouza/Restfox/assets/89777185/2eee5a4b-7b0a-4792-bd81-5792aebb5048">
Now after calling a request it fails and checking Request tab in response I see that client_secret value is changed by "25" added in between:
<img width="870" alt="image" src="https://github.com/flawiddsouza/Restfox/assets/89777185/b2d9b190-1717-4b10-9778-bb8b8a2ca065">

Using version: Version 0.2.1 (0.2.1)

**Comment by flawiddsouza** [comment] 2023-11-27 14:16
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/7e460cf5-30a7-411a-9680-06763e5184e0)
Hi, this is not a bug. It's just url encoded. It will be decoded correctly by your http server if what you meant to send was `%40`. If you meant to send `@` as in `M4v@403d`, you should just use `@` instead of `%40`. It will be automatically url encoded to `%40`.

**Comment by flawiddsouza** [comment] 2023-12-05 19:19
Closing this issue for now, as there's no reply. Let me know if there's still an issue after following the above steps.

**Closed by flawiddsouza** 2023-12-05 19:19 UTC
