### ISSUE TITLE
Required request body is missing

### ISSUE THREAD

**Issue by anarckk** [flawiddsouza/Restfox#45] opened 2023-06-05 09:39 UTC
![Snipaste_2023-06-05_17-38-26](https://github.com/flawiddsouza/Restfox/assets/27038948/e5a64b65-ce7c-4692-b241-770549bbcea8)

**Comment by flawiddsouza** [comment] 2023-06-06 16:27
Hi @anarckk, please provide your backend code for this request handler so I can have a better understanding of what's happening. It seems like this is an error in your code rather than in Restfox. "Required request body is missing: public". There's no public in the request json you're sending.

**Comment by anarckk** [comment] 2023-06-08 01:15
Hi, My backend code is correct, because I use postman is ok.
here is my code, just simple test interface
![image](https://github.com/flawiddsouza/Restfox/assets/27038948/b86656d9-5a6d-463c-bc19-38b9955e10e3)
and postman request
![image](https://github.com/flawiddsouza/Restfox/assets/27038948/55f8d506-2b08-4b40-96a6-fe55702f38ea)
docker-compose.yaml
```
version: '3'

services:
  restfox:
    image: restfox:latest
    container_name: restfox
#    ports:
#      - 4004:4004
    environment:
      TZ: Asia/Shanghai
    networks:
      custom-bridge:
    restart: unless-stopped
    logging:
      options:
        max-size: "100m"
networks:
  custom-bridge:
    external: true
```

If I directly use `localhost`, it can't connect. so I use docker dns address, it can connect.
![image](https://github.com/flawiddsouza/Restfox/assets/27038948/c2499c20-1632-42fe-a7bc-b1c604063540)

Can you help me solve this problem? it you need anything else information, tell me.

**Comment by flawiddsouza** [comment] 2023-06-08 01:55
Not being able to directly use localhost makes sense, as localhost inside the docker container would be different from your system's localhost. Using the docker dns address is the right solution for that. This would be the limitation of using docker for running Restfox.

Regarding the request issue, can I see what's in the headers tab for both Postman and Restfox? Usually when Content-Type application/json header is missing, some frameworks are unable to parse json bodies. But Restfox will add that header by default, so it might be a different issue. Do a test by adding all the headers you find in Postman's headers tab into the Restfox headers tab. See if that changes anything.

**Comment by anarckk** [comment] 2023-06-08 05:43
ok
![image](https://github.com/flawiddsouza/Restfox/assets/27038948/aaf3cc14-ee08-426c-8bc0-052c337b7bfe)

![image](https://github.com/flawiddsouza/Restfox/assets/27038948/9760f737-7158-4728-afb1-63c307bf9272)

**Comment by anarckk** [comment] 2023-06-08 05:58
can't fix me problem
![image](https://github.com/flawiddsouza/Restfox/assets/27038948/2f0a2dfd-d9a2-476d-842f-4e8522a3c293)

**Comment by flawiddsouza** [comment] 2023-06-08 14:20
That's very very odd. Can you share a minimal reproduction of the backend code that's causing the issue as a zip file or a git repo, so I can test from my side? I'm not able do anything without being able to reproduce this issue from my side. I would like to know why this is happening.

**Comment by anarckk** [comment] 2023-06-09 02:01
ok, I will share you later

**Comment by flawiddsouza** [comment] 2023-09-02 05:00
@anarckk Is there any update here? I'll close this issue if it's something we cannot reproduce. We can reopen this in the future if someone faces the same issue again.

**Comment by flawiddsouza** [comment] 2023-09-21 19:22
Hi @anarckk, this issue should be fixed with my latest commit: https://github.com/flawiddsouza/Restfox/commit/a14216bcd85b681a99c572d41be6ada87be4252d. Will be pushing a docker image update soon.

**Closed by flawiddsouza** 2023-09-21 19:22 UTC
Labels: bug, web-standalone
