### ISSUE TITLE
Can we have A Persistant Storage for the application

### ISSUE THREAD

**Issue by silkadmin** [flawiddsouza/Restfox#250] opened 2024-09-22 14:36 UTC
Hi, the application is great and simple with easy learning curve. I want to use this with my team.

Can you guide me how to enable a persistant storage such that we can share the collection with my team,

Thank you
Bismay M

**Comment by flawiddsouza** [comment] 2024-09-22 16:15
Hi, you can already do this using file workspaces in the the desktop versions of Restfox. Desktop versions of Restfox are available here: https://github.com/flawiddsouza/Restfox/releases/tag/v0.26.0.

First you need a create a file workspace, by clicking Add workspace:
![image](https://github.com/user-attachments/assets/b8647dbe-db42-4731-b000-3b7aeb452eb5)

As you can see, the type is set to "In Filesystem (Git Friendly).
![image](https://github.com/user-attachments/assets/9000f582-53bd-4c7d-bd6f-4dc42eb75fb3)

This workspace can be pushed to a git repo or can be synced using any other kind of sync solution.

Then your team, can clone the git repo with the collection and open the collection by using this option:
![image](https://github.com/user-attachments/assets/ef5cf373-2bb2-4124-84bd-c8c67fb84288)

This allows you to collaborate with the same collection.

**Comment by lilleman-tw** [comment] 2024-10-12 09:03
This does not seem to exist when running from a container?
![Screenshot from 2024-10-12 11-02-51-1](https://github.com/user-attachments/assets/ebd862df-faaf-48fa-b377-4217b259a910)

**Comment by flawiddsouza** [comment] 2024-10-12 09:18
Yes, that's correct. As you can't use your local file system inside a container without mounting.

**Comment by lilleman-tw** [comment] 2024-10-12 14:41
But mounting is very doable. :) It would be very helpful with the option to save to a local folder even in web mode, especially for a team where we could share Restfox as part of a docker compose.

**Comment by flawiddsouza** [comment] 2024-10-12 15:38
Mounting is doable but the implementation of file workspaces is very dependent on the desktop / electron code. There's no simple copy paste solution to enable this feature for the docker version.

There's already a feature request open for persisting docker data:
https://github.com/flawiddsouza/Restfox/issues/92

Definitely looking into enabling this for the docker version as well.

**Comment by flawiddsouza** [comment] 2024-10-13 05:29
Duplicate of #92

**Closed by flawiddsouza** 2024-10-13 05:29 UTC
