### ISSUE TITLE
Cannot start Restfox twice

### ISSUE THREAD

**Issue by WolfgangHG** [flawiddsouza/Restfox#87] opened 2023-12-11 16:00 UTC
By accident I noticed that you cannot start another Restfox instance if it is already running: the second window just stays blank besides the title bar:
![image](https://github.com/flawiddsouza/Restfox/assets/138049/7e0fb533-3eb6-45b2-9b19-412a76a6d4bb)

This is not really a problem but it irritated me the first time ;-)

**Comment by flawiddsouza** [comment] 2023-12-17 06:15
I'll keep this open but Restfox is currently not designed to be run in two windows. As data doesn't sync between windows if it's modified in one window. The issue you're describing seems to be caused by electron getting an exclusive lock on the indexeddb store, for one window, so the other window isn't able to access it. Will be moving to sqlite / some other store for electron in the near future. That should fix this and allow you to open two windows of Restfox.

**Comment by flawiddsouza** [comment] 2023-12-17 06:16
I'll keep this open but Restfox is currently not designed to be run in two windows. As data doesn't sync between windows if it's modified in one window. The issue you're describing seems to be caused by electron getting an exclusive lock on the indexeddb store, for one window, so the other window isn't able to access it. Will be moving to sqlite / some other store for electron in the near future. That should fix this and allow you to open two or more windows of Restfox.

**Comment by WolfgangHG** [comment] 2023-12-17 10:20
In my mind there is no need to invest too much time in starting Restfox twice. It would be OK if the second instance shows an error message "already running" and then closes. The way I use it, I can't think of starting two Restfox instances and working in both.

**Comment by codecat** [comment] 2024-03-12 12:45
I just ran into this as well and got scared that Restfox suddenly deleted all my workspaces. Turns out there was another instance running in the background. Some kind of error would be really appreciated here.

**Comment by flawiddsouza** [comment] 2024-03-12 20:15
Sorry about that. Will prioritize this for the next release.

**Comment by flawiddsouza** [comment] 2024-03-16 08:07
This is now resolved as of commit: 7c8bd5459f0df34909d20b421631da33f99a71a8. Will be available in the next release.

**Closed by flawiddsouza** 2024-03-16 08:07 UTC
Labels: bug
